version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  user_service:
    cmds:
      - docker buildx build --platform linux/amd64 -t phathdt379/user_service:latest -f services/user_service/Dockerfile .
