apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service
spec:
  selector:
    matchLabels:
      app: user_service
  template:
    metadata:
      labels:
        app: user_service
    spec:
      containers:
        - name: user_service
          image: phathdt379/user_service
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 4000
